language: minimal

services:
  - docker

script:
  - docker --version
  - docker-compose -f docker-compose-build.yaml build

deploy:
  provider: script
  script: bash scripts/docker_push.sh
  on:
    branch: main
